# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出价')),
                ('buser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Carinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, null=True, verbose_name='车两信息')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='出价')),
                ('orderStatus', models.IntegerField(choices=[(0, '已出价'), (1, '已支付'), (2, '交易成功'), (3, ''), (4, '')], default=0, verbose_name='订单状态')),
                ('orderNo', models.CharField(max_length=50, verbose_name='订单号')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('buy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buser', to=settings.AUTH_USER_MODEL)),
                ('sale_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
