# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-25 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20180925_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bnak',
            new_name='Bank',
        ),
    ]
