# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=50, verbose_name='品牌名称')),
                ('logo_brand', models.ImageField(default='', upload_to='img/logo', verbose_name='logo')),
                ('isDelete', models.BooleanField(default='', verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Carinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=30, verbose_name='车名')),
                ('regist', models.DateField(verbose_name='上牌日期')),
                ('enginNo', models.CharField(max_length=50, verbose_name='发动机号')),
                ('mileage', models.IntegerField(default=0, verbose_name='公里数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('color', models.CharField(max_length=10, null=True, verbose_name='颜色')),
                ('maintenance', models.CharField(max_length=200, null=True, verbose_name='维修记录')),
                ('extractprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价格')),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新车价格')),
                ('picture', models.ImageField(default='', upload_to='img/car', verbose_name='汽车图片')),
                ('formalities', models.BooleanField(default=True, verbose_name='手续是否齐全')),
                ('debt', models.BooleanField(default=False, verbose_name='是否有债务')),
                ('promise', models.TextField(null=True, verbose_name='卖家承诺')),
                ('examine', models.IntegerField(choices=[(0, '审核中'), (1, '审核通过'), (2, '审核不通过')], default=0, verbose_name='审核进度')),
                ('isPurchase', models.BooleanField(default='', verbose_name='是否购买')),
                ('isDelete', models.BooleanField(default='', verbose_name='是否删除')),
                ('serbran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
